# Movie Recommendation System

## Load Dataset

In [1]:
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/iPriyadarshi/MachineLearning-BCS4706/main/dataset/tmdb_5000_movies.csv"
movies = pd.read_csv(url)

In [3]:
movies.sample(5)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
3142,10000000,"[{""id"": 28, ""name"": ""Action""}]",NaN,250066,"[{""id"": 380, ""name"": ""brother brother relation...",en,American Heist,"Two brothers, both with troubled paths, find t...",11.431434,"[{""name"": ""NGN Productions"", ""id"": 7587}, {""na...","[{""iso_3166_1"": ""CA"", ""name"": ""Canada""}, {""iso...",2014-09-11,0,94.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Brothers in arms for life.,American Heist,4.3,158
4779,0,"[{""id"": 35, ""name"": ""Comedy""}]",NaN,14022,"[{""id"": 305, ""name"": ""moon""}, {""id"": 490, ""nam...",en,Slacker,"Presents a day in the life in Austin, Texas am...",3.320622,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1990-07-27,0,97.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Slacker,6.4,77
4270,1300000,"[{""id"": 18, ""name"": ""Drama""}]",http://nimbusfilm.dk/film/festen/?lang=en,309,"[{""id"": 236, ""name"": ""suicide""}, {""id"": 494, ""...",da,Festen,A grandiose party to celebrate a sixtieth birt...,10.240917,"[{""name"": ""Nordic Film"", ""id"": 156}, {""name"": ...","[{""iso_3166_1"": ""DK"", ""name"": ""Denmark""}, {""is...",1998-05-20,0,105.0,"[{""iso_639_1"": ""da"", ""name"": ""Dansk""}, {""iso_6...",Released,NaN,The Celebration,7.7,207
1351,37000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 53, ""name...",http://whatdoyoubelieve.warnerbros.com/,48171,"[{""id"": 716, ""name"": ""vatican""}, {""id"": 8608, ...",en,The Rite,Seminary student Michael Kovak (Colin O'Donogh...,11.492474,"[{""name"": ""New Line Cinema"", ""id"": 12}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2011-01-28,96047633,114.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,You can only defeat it when you believe.,The Rite,5.8,556
3609,20000000,"[{""id"": 10749, ""name"": ""Romance""}, {""id"": 35, ...",http://50shadesofblackmovie.com/,351819,"[{""id"": 572, ""name"": ""sex""}, {""id"": 9215, ""nam...",en,Fifty Shades of Black,An inexperienced college student meets a wealt...,14.947588,"[{""name"": ""Open Road Films (II)"", ""id"": 16313}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-01-28,21164799,92.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Way shadier than gray.,Fifty Shades of Black,4.3,331

In [4]:
movies.shape

(4803, 20)

In [5]:
url = "https://raw.githubusercontent.com/iPriyadarshi/MachineLearning-BCS4706/main/dataset/tmdb_5000_credits.csv"
credits = pd.read_csv(url,encoding='latin1')

In [6]:
credits.sample(5)

,movie_id,title,cast,crew
365,686,Contact,"[{""cast_id"": 5, ""character"": ""Eleanor Arroway""...","[{""credit_id"": ""52fe426ac3a36847f801ce85"", ""de..."
2416,38117,Beastly,"[{""cast_id"": 4, ""character"": ""Kyle Kingson"", ""...","[{""credit_id"": ""575700359251414eb100011a"", ""de..."
4527,33430,Twin Falls Idaho,"[{""cast_id"": 2, ""character"": ""Blake Falls"", ""c...","[{""credit_id"": ""58ebc7f7925141281908b4da"", ""de..."
2307,2757,Adaptation.,"[{""cast_id"": 4, ""character"": ""Charlie/Donald K...","[{""credit_id"": ""52fe436ac3a36847f8052983"", ""de..."
2935,167073,Brooklyn,"[{""cast_id"": 0, ""character"": ""Eilis Lacey"", ""c...","[{""credit_id"": ""53d14ac70e0a265dfa00cec3"", ""de..."

In [7]:
credits.shape

(4803, 4)

## Merge Datasets by "title"

In [8]:
df = movies.merge(credits, on = 'title')

In [9]:
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
df.shape

(4804, 23)

In [11]:
df.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count,movie_id
count,4.804000e+03,4804.000000,4804.000000,4.804000e+03,4802.000000,4804.000000,4804.000000,4804.000000
mean,2.904802e+07,57151.612198,21.493532,8.232690e+07,106.904415,6.093505,690.645087,57151.612198
std,4.071946e+07,88693.112486,31.817249,1.629120e+08,22.603522,1.193718,1234.748000,88693.112486
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,5.000000
25%,7.950000e+05,9011.250000,4.666750,0.000000e+00,94.000000,5.600000,54.000000,9011.250000
50%,1.500000e+07,14623.500000,12.913104,1.916124e+07,104.000000,6.200000,235.000000,14623.500000
75%,4.000000e+07,58639.500000,28.294992,9.293886e+07,118.000000,6.800000,737.250000,58639.500000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000,459488.000000

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4804 entries, 0 to 4803
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4804 non-null   int64
 1   genres                4804 non-null   str
 2   homepage              1712 non-null   str
 3   id                    4804 non-null   int64
 4   keywords              4804 non-null   str
 5   original_language     4804 non-null   str
 6   original_title        4804 non-null   str
 7   overview              4801 non-null   str
 8   popularity            4804 non-null   float64
 9   production_companies  4804 non-null   str
 10  production_countries  4804 non-null   str
 11  release_date          4803 non-null   str
 12  revenue               4804 non-null   int64
 13  runtime               4802 non-null   float64
 14  spoken_languages      4804 non-null   str
 15  status                4804 non-null   str
 16  tagline               3961 non-null   str
 17  title                 4804 non-null   str
 18  vote_average          4804 non-null   float64
 19  vote_count            4804 non-null   int64
 20  movie_id              4804 non-null   int64
 21  cast                  4804 non-null   str
 22  crew                  4804 non-null   str
dtypes: float64(3), int64(5), str(15)
memory usage: 39.1 MB

## Select Important Columns

In [13]:
df = df[['movie_id','title','overview','genres','keywords','cast','crew']]

In [14]:
df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

## Handle Missing Values

In [15]:
df.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [16]:
# Remove rows with missing values
df.dropna(inplace=True)

## Convert Strings to Python List

In [17]:
import ast

# Function to extract genre and keywords
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name'])
    return L

In [18]:
df['genres'] = df['genres'].apply(convert)
df['keywords'] = df['keywords'].apply(convert)

In [19]:
# Function to get first 3 cast members
def convert_cast(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter != 3:
            L.append(i['name'])
            counter += 1
        else:
            break
    return L

df['cast'] = df['cast'].apply(convert_cast)

In [20]:
# Function to get director name
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

df['crew'] = df['crew'].apply(fetch_director)

In [21]:
# Convert overview sentence into list of words
df['overview'] = df['overview'].apply(lambda x:x.split())

In [22]:
# Remove spaces from Names

df['genres'] = df['genres'].apply(lambda x:[i.replace(" ","") for i in x])
df['keywords'] = df['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
df['cast'] = df['cast'].apply(lambda x:[i.replace(" ","") for i in x])
df['crew'] = df['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [23]:
# Combine all important columns to create new 'tags' column
df['tags'] = df['overview'] + df['genres'] + df['keywords'] + df['cast'] + df['crew']

In [24]:
df

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...,...,...,...,...,...
4799,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[Action, Crime, Thriller]","[unitedstates–mexicobarrier, legs, arms, paper...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez],"[El, Mariachi, just, wants, to, play, his, gui..."
4800,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...","[Comedy, Romance]",[],"[EdwardBurns, KerryBishé, MarshaDietlein]",[EdwardBurns],"[A, newlywed, couple's, honeymoon, is, upended..."
4801,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Comedy, Drama, Romance, TVMovie]","[date, loveatfirstsight, narration, investigat...","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith],"[""Signed,, Sealed,, Delivered"", introduces, a,..."
4802,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...",[],[],"[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia],"[When, ambitious, New, York, attorney, Sam, is..."
4803,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...",[Documentary],"[obsession, camcorder, crush, dreamgirl]","[DrewBarrymore, BrianHerzlinger, CoreyFeldman]","[BrianHerzlinger, JonGunn, BrettWinn]","[Ever, since, the, second, grade, when, he, fi..."

## Create new DataFrame

In [25]:
new_df = df[['movie_id','title','tags']].copy()

In [26]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4799,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4800,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4801,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4802,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4803,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [27]:
# Convert Tags into string
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [28]:
new_df

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
4799,9367,El Mariachi,El Mariachi just wants to play his guitar and ...
4800,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...
4801,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4802,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4803,25975,My Date with Drew,Ever since the second grade when he first saw ...

## Convert Text to Numerical Vectors

In [29]:
from sklearn.feature_extraction.text import CountVectorizer

# Create CountVectorizer object
cv = CountVectorizer(max_features=5000, stop_words='english')

# Convert tags to vectors
vectors = cv.fit_transform(new_df['tags']).toarray()

## Calculate Similarity:

Cosine similarity measures how similar two movies are.

In [30]:
from sklearn.metrics.pairwise import cosine_similarity

# Calculate cosine similarity between movies
similarity = cosine_similarity(vectors)
print(similarity)

[[1.         0.08838835 0.05892557 ... 0.02457366 0.02602896 0.        ]
 [0.08838835 1.         0.0625     ... 0.0260643  0.         0.        ]
 [0.05892557 0.0625     1.         ... 0.0260643  0.         0.        ]
 ...
 [0.02457366 0.0260643  0.0260643  ... 1.         0.06907969 0.04783649]
 [0.02602896 0.         0.         ... 0.06907969 1.         0.05066946]
 [0.         0.         0.         ... 0.04783649 0.05066946 1.        ]]

## Recommendation Function

In [31]:
# Function to recommend movies
def recommend(movie):

    # Get index of movie
    movie_index = new_df[new_df['title'] == movie].index[0]

    # Get similarity scores
    distances = similarity[movie_index]

    # Sort movies based on similarity score
    movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]

    # Print recommended movies
    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [32]:
recommend("Spider-Man 2")

Spider-Man 3
Spider-Man
The Amazing Spider-Man 2
The Amazing Spider-Man
Hellboy II: The Golden Army